#!/usr/bin/env bash
# episodic-sync.sh — Sync episodic memory from layer-stage system to Claude Code auto-memory
#
# Discovers all outputs/episodic/index.md files across the hierarchy,
# extracts recent sessions and key decisions, and generates a single
# topic file at ~/.claude/projects/<project>/memory/episodic.md
#
# Usage:
#   episodic-sync.sh [REPO_ROOT]
#
# If REPO_ROOT is not provided, defaults to the parent of tools/ (where this script lives).

set -euo pipefail

# Determine repo root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${1:-$(dirname "$SCRIPT_DIR")}"

# Determine auto-memory directory
MEMORY_DIR="$HOME/.claude/projects/-home-dawson/memory"

if [ ! -d "$MEMORY_DIR" ]; then
    echo "ERROR: Auto-memory directory not found: $MEMORY_DIR"
    echo "Make sure Claude Code has been used in this project at least once."
    exit 1
fi

OUTPUT_FILE="$MEMORY_DIR/episodic.md"

# Find all episodic index.md files
mapfile -t INDEX_FILES < <(find "$REPO_ROOT" -path "*/outputs/episodic/index.md" -type f 2>/dev/null | sort)

if [ ${#INDEX_FILES[@]} -eq 0 ]; then
    echo "No episodic index.md files found under $REPO_ROOT"
    exit 0
fi

echo "Found ${#INDEX_FILES[@]} episodic index files"

# extract_section: Pull a markdown section from a file
# Usage: extract_section "FILE" "## Section Name"
# Returns content between the heading and the next ## or ---
extract_section() {
    local file="$1"
    local heading="$2"
    sed -n "/^${heading}/,/^---\|^## [^#]/p" "$file" | head -n -1 | tail -n +2 || true
}

# extract_table: From section content, pull table header (2 lines) + up to N data rows
# Usage: echo "$CONTENT" | extract_table [N]
extract_table() {
    local limit="${1:-5}"
    local header data
    header=$(grep -E '^\|' | head -2) || true
    if [ -z "$header" ]; then
        return
    fi
    # Re-read stdin is consumed, so we need a different approach
    echo "$header"
}

# render_section: Extract a section, output as table or list (whichever format it's in)
# Usage: render_section "FILE" "## Section Name" "### Output Heading" [max_rows]
render_section() {
    local file="$1"
    local src_heading="$2"
    local out_heading="$3"
    local max_rows="${4:-5}"

    if ! grep -q "$src_heading" "$file" 2>/dev/null; then
        return
    fi

    local content
    content=$(extract_section "$file" "$src_heading")
    if [ -z "$content" ]; then
        return
    fi

    echo "$out_heading"
    echo ""

    # Check if content has markdown tables
    local table_header table_data
    table_header=$(echo "$content" | grep -E '^\|' | head -2 || true)

    if [ -n "$table_header" ]; then
        # Table format — output header + limited data rows
        echo "$table_header"
        table_data=$(echo "$content" | grep -E '^\|' | tail -n +3 | head -"$max_rows" || true)
        if [ -n "$table_data" ]; then
            echo "$table_data"
        fi
    else
        # List or prose format — output first N lines
        echo "$content" | head -"$max_rows"
    fi
    echo ""
}

# Start building output
{
    echo "# Episodic Memory (synced)"
    echo ""
    echo "Aggregated from \`outputs/episodic/index.md\` files across the layer-stage hierarchy."
    echo "**Last synced**: $(date '+%Y-%m-%d %H:%M')"
    echo "**Source count**: ${#INDEX_FILES[@]} episodic directories"
    echo ""
    echo "---"

    for INDEX_FILE in "${INDEX_FILES[@]}"; do
        # Derive relative path from repo root for the section heading
        REL_PATH="${INDEX_FILE#$REPO_ROOT/}"
        # Strip outputs/episodic/index.md to get the layer path
        LAYER_PATH="${REL_PATH%/outputs/episodic/index.md}"

        echo ""
        echo "## $LAYER_PATH"
        echo ""

        # Extract metadata lines
        META=$(grep -E '^\*\*(Layer|Location|Last Updated|Total Sessions)\*\*' "$INDEX_FILE" 2>/dev/null || true)
        if [ -n "$META" ]; then
            echo "$META"
            echo ""
        fi

        # Extract standard sections
        render_section "$INDEX_FILE" "## Recent Sessions" "### Recent Sessions" 5
        render_section "$INDEX_FILE" "## Key Decisions" "### Key Decisions" 5
        render_section "$INDEX_FILE" "## Active Work" "### Active Work" 5

        # Synthesis reference (compact — just first 3 lines)
        if grep -q "## Synthesis" "$INDEX_FILE" 2>/dev/null; then
            local_synth=$(extract_section "$INDEX_FILE" "## Synthesis" | head -3 || true)
            if [ -n "$local_synth" ]; then
                echo "### Synthesis"
                echo ""
                echo "$local_synth"
                echo ""
            fi
        fi

        echo "**Source**: \`$REL_PATH\`"
        echo ""
        echo "---"
    done

    echo ""
    echo "*Auto-generated by \`tools/episodic-sync.sh\` — do not edit directly.*"
    echo "*Edit the source \`outputs/episodic/index.md\` files instead.*"
} > "$OUTPUT_FILE"

echo "Generated: $OUTPUT_FILE"
echo "Sections: ${#INDEX_FILES[@]}"
